version: '3.9'
services:
  db:
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: P4o3l8l1
      MYSQL_USER: docker
      MYSQL_PASSWORD: P4o3l8l1
      MYSQL_DATABASE: Banco
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - petcontrol-network
  petcontrolv2:
    image: gsagahc/petcontrolv2
    restart: always
    build: ../br.com.pet.control.v2
    working_dir: /br.com.pet.control.v2

    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/Banco?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: P4o3l8l1
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - petcontrol-network
networks:
  petcontrol-network:
    driver: bridge